apiVersion: v1
data:
  event-service.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      httpListenAddress: common.httpListenAddress,
      grpcServers: [{
        listenAddresses: [':8985'],
        authenticationPolicy: { allow: {} },
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    }

kind: ConfigMap
metadata:
  name: event-service
  namespace: buildbarn
